"""empty message

Revision ID: 707d23bce7d3
Revises: e26d54fdde5b
Create Date: 2020-03-17 14:11:49.936256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '707d23bce7d3'
down_revision = 'e26d54fdde5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('handler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password', sa.Binary(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_handler_id'), 'handler', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_handler_id'), table_name='handler')
    op.drop_table('handler')
    # ### end Alembic commands ###
